### ISSUE TITLE
extra app.js

### ISSUE THREAD

**Issue by tom76kimo** [nuts1221stun/ahooopsy#1]
I think maybe we don't need the code in `app.js`?

Since we have already rendered the components in `route.js`. https://github.com/nuts1221stun/ahooopsy/blob/master/routes.js#L15-L18

and https://github.com/nuts1221stun/ahooopsy/blob/master/app.js#L7-L10 will render the `<Main />` again.

We can simply marked all the code inside `app.js` and see the main page still can render correctly. Besides, `app.js` will always overwrite the components which rendered from `route.js`.

**Comment by nuts1221stun** [comment]
You're right! Thanks a lot! :+1:

**Comment by tom76kimo** [comment]
Marked code in `app.js`
